import LatestUpdate from '@/app/components/Title/LatestUpdate/LatestUpdate';
import React from 'react'

export const metadata = {
    title: "Latest Updates",
    description: "Generated by create next app",
  };
export default function latest() {
  return (
    <>
    <LatestUpdate>
    </LatestUpdate>
    </>
  )
}
