
// export const metadata = {
//     title: "Advanced Search",
//     description: "Generated by create next app",
//   };

import NavbarProvider from "@/app/components/NavbarProvider";

export default function LayoutTitle({ children }) {
    return (
        <>
            <NavbarProvider>
                {children}
            </NavbarProvider>
        </>
    )
}
