import RecentlyAdded from '@/app/components/Title/RecentlyAdded/RecentlyAdded';
import React from 'react'

export const metadata = {
    title: "Recently Added",
    description: "Generated by create next app",
  };
export default function latest() {
  return (
    <>
    <RecentlyAdded>
      
    </RecentlyAdded>
    </>
  )
}