import Create from '@/app/components/Title/Create/Create';
import React from 'react'

export const metadata = {
  title: "Create",
  description: "Generated by create next app",
};
export default function CreateTitle() {
  return (
    <>
      <Create>
      </Create>
    </>
  )
}
